pipeline {
	agent any
	stages {
		stage ('sample03 pipeline') {
			steps {
				//Node: sh need be running on Lunux OS
				// sh '''
				// 	TOKEN="test-token"
				// 	GROUP_ID="-000000000"
				// 	CODE=$(curl -o /dev/null -s -w %{http_code} www.example.com)
				// 	if [ "${command}" != "200" ]; then
                //       message="www.example.com response code != 200."
                //       curl -X GET "https://api.telegram.org/bot${TOKEN}/sendMessage" \
                //           -d "chat_id=${GROUP_ID}&text=${message}"
                //     fi 
				// '''

				//Node bat running on Windows OS

				withCredentials([string(credentialsId: 'test-token', variable: 'TOKEN')]){
					bat '''
						for /F %I in ('curl -o /dev/null -s -w %{http_code} www.example.com') do set HTTP=%I
						if "%HTTP%" == "200" (
						    echo successed
						    echo %TOKEN%
						    exit /b 0
						) else (
						    echo failed
						    exit /b 1
						)

					'''
				}
			}
		}
	}
}